### ISSUE TITLE
Could not find function “kable”

### ISSUE THREAD

**Issue by lker5lker5** [KarasiewiczStephane/WitOMI#5]
I tried to run the command you've given, and for the kable one, it prompts that the there is no kable function. Could you please give me a hint about this one? Million thanks. Btw, is there a documentation to explain how to read these graphs?

**Comment by lker5lker5** [comment]
Sorry, I missed the first part, should install knitr package first. Still want to know **how to parse the diagram**. I've cheked one of the references, **the axes show the weighting percentages**, how to make it happen here? Thanks.

**Comment by KarasiewiczStephane** [comment]
Hello,
  I'll need more precision on which diagram would you like me to explain in more details, as their is so many of them.  
 I think what you are looking for the is in "summary(subniche)" and will correspond to the value find under Projected inertia (%). If you want to make them appear on the diagram you will have to use the function "legend" (https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/legend.html)  and included yourself.
