### ISSUE TITLE
Errror with plot(subnic1) 

### ISSUE THREAD

**Issue by UJSR88** [KarasiewiczStephane/WitOMI#7]
Everything goes fine when calculating other parameters, but when using "plot(subnic1)" function, the following message appears:

Error in `[.data.frame`(y, , subnam[j]) : undefined columns selected

Also, when calculating: subplot_sp(subnic1,"Neba",main="Species subniche in K")....instead of "Neba", I choose one species code from my own set, but the same previous error is prompted. Such error doesn´t shows when using example data (drome or adecheinv). Any suggestion on how to fix this issue??
Thanks a lot in advance

**Comment by KarasiewiczStephane** [comment]
Hi thanks for the report,
The error was caused by the function subarea which creates the list of polygons for the plotting functions. It only allowed factor with numeric levels (ex: 1,2,3) instead of characters ("Spring", "Summer", ...). But I have now uploaded the corrected function.
